### ISSUE TITLE
Warning in doc jobs

### ISSUE THREAD

**Issue by dirk-thomas** [ros/roslisp#40]
In the latest doc jobs (e.g. http://build.ros.org/job/Ldoc__ros_comm__ubuntu_xenial_amd64/32 and http://build.ros.org/view/Ldoc/job/Ldoc__roslisp_common__ubuntu_xenial_amd64/3/) the following warning has started to show up:

> WARNING:
> Couldn't re-execute SBCL with proper personality flags (/proc isn't mounted? setuid?)

The best description I was able to find was https://github.com/dimitri/pgloader/wiki/Running-in-Docker-(SBCL-warning)

Since this package is pulling in the dependency on SBCL can you please come up with a patch how this warning can be avoided since it makes the doc job of multiple packages unstable.

**Comment by airballking** [comment]
@dirk-thomas Thanks for pointing this out! @gaya- and me are attending IROS this week. Once we're back in Bremen, we'll have a look into this.

**Comment by dirk-thomas** [comment]
@airballking @gaya- Any news on this?

**Comment by gaya-** [comment]
@airballking are you still at it or should I look into it?

**Comment by airballking** [comment]
@gaya- I haven't had time to look at this issue. If you could do it, I would be grateful.

**Comment by gaya-** [comment]
@dirk-thomas This warning happens because docker's seccomp (secure computation) mode enables Address Space Layout Randomization technique, which makes it more difficult for processes to corrupt other processes' memory. SBCL tries to turn off ASLR for its own process, as its ok to do that for yourself if you're not worried about others corrupting your memory. Usually Linux allows this but Docker doesn't per default. SBCL only supports ASLR mode partially, hence the warning. I can see the following solutions to this problem:

* allow Docker to turn off ASLR for SBCL using a [Docker config file](https://github.com/daewok/slime-docker/blob/master/resources/docker-sbcl-seccomp.json), which will allow processes to call the OS `personality()` [function](http://man7.org/linux/man-pages/man2/personality.2.html)
* completely disable seccomp, it was only added in the newest version of Docker and the previous versions were fine without it (assuming, of course, that the software built by the farm doesn't try to corrupt fellow software)
* add a patch to SBCL to muffle the warning
* make Jenkins ignore the SBCL warning

Coming up with a clean fix on the SBCL side would mean to implement support for ASLR, whereas currently the compiler expects fixed memory maps. That is not feasible for me :)

**Comment by dirk-thomas** [comment]
@nuclearsandwich @tfoote Can either of you comment if we can either turn off ASLR in Docker on the farm (first option) or completely disable seccomp (second option)?

**Comment by airballking** [comment]
@gaya- Again, thanks for looking into this!

**Comment by tfoote** [comment]
I'm not familiar with either option.

**Comment by gaya-** [comment]
I would probably go with only allowing [`personality()`](http://man7.org/linux/man-pages/man2/personality.2.html) calls, which basically only manages the way the OS will set up the memory for the process, as far as I understand. There is nothing dangerous there, as the process can only set things for itself and not others. I'm not a Docker expert and don't know if there is a shorter way to give a process access to a specific OS function call than by using a config file. If there isn't and the build farm uses a non-default config, one would have to maintain that file. So that's the downside.

**Comment by nuclearsandwich** [comment]
I would prefer not to disable seccomp entirely. The personality syscall is [specifically un-whitelisted to prevent BSD emulation which is very untested within Docker](https://docs.docker.com/engine/security/seccomp/#significant-syscalls-blocked-by-the-default-profile).  I have to re-up my seccomp knowledge in more detail but it looks like it's possible to whitelist syscalls with a subset of arguments enabling us to allow processes to disable ASLR without changing the execution persona to emulate another unix.

If we can't enable ASLR deactivation without also enabling BSD emulation I think it's potentially worth attempting to squelch the warning in the script or Jenkins config. We're already stretched for operations time and I'd like not to stray too far from defaults without being able to spend time investigating the potential side effects.

**Comment by gaya-** [comment]
@nuclearsandwich I haven't used the buildfarm scripts to reproduce the issue but we used a local docker installation on Ubuntu 16.04 with the default configuration (docker version 17.04.0-ce) and got the same warning when running "$ sbcl" in it. From what I can see from these lines of the build log:

```
Security Options:
 apparmor
 seccomp
  Profile: default
```

the seccomp profile used on the buildfarm is also the default one.

I haven't tested the seccomp.json myself unfortunately but I trust that @daewok knew what he was doing when he wrote it. It might get outdated, though, so don't know what the maintenance status there is.

**Comment by nuclearsandwich** [comment]
Took another look this morning. The only difference between the Docker default seccomp profile and the suggested one is the addition of the personality syscall to the unconditional whitelist.

I would prefer that we only whitelist the personality calls needed by SBCL to properly  set ASLR so I went to review them [here](https://github.com/sbcl/sbcl/blob/7aa16ffc71fb5c04458297978292daa7f3f37dac/src/runtime/linux-os.c#L262-L308) and there are a few other personality calls that it sets which include re-applying the fetched personality, so maybe there's no way to restrict it further and still allow SBCL to do what it needs.

Due to the seccomp v1 vs seccomp-bpf/v2 search muddying I'm actually having trouble finding reliable docs on whether I can use a mask comparison when whitelisting the personality commands. If anyone on-thread has more direct experience please chime in.

**Comment by nuclearsandwich** [comment]
While examining job configurations I noticed that we do [ignore one warning](https://github.com/ros-infrastructure/ros_buildfarm/blob/614a3c0170b54cb86c6159612e41385e63859b12/ros_buildfarm/templates/snippet/builder_system-groovy_extract-warnings.xml.em#L18) but because of the split line I'm not sure that will work without some very special handling.

**Comment by gaya-** [comment]
@nuclearsandwich Well, with some smarter regexp pattern it is definitely possible to find warnings that take more than one line. If taking 2 lines per warning can be agreed upon, ignoring the SBCL warning would be possible. So instead of one readLine() concatenate 2 with a linebreak and have the regexp consider that linebreak. Just ignoring the warning is not the cleanest solution but I don't think it will cause any problems. It hasn't until now. SBCL is barely used on the build farm, only for a couple of scripts.

**Comment by nuclearsandwich** [comment]
I've just deployed a change to build.ros.org agents (https://github.com/ros-infrastructure/buildfarm_deployment/pull/194) which whitelists the personality system call within docker. I couldn't determine a reliable way to limit the system call use to just ASLR disablement but I think that's just my lack of understanding and it could probably be done with a bit of work.

The doc jobs no longer exhibit the warning since the system call can now be used and the separate warning about using a non-default seccomp profile is being ignored (https://github.com/ros-infrastructure/ros_buildfarm/pull/527) so I think this issue can be closed.

**Comment by dirk-thomas** [comment]
I just triggered the two referenced doc jobs and now they pass. :+1:
